//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34209
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pmd2mqoGUI {
	using System;
	
	
	/// <summary>
	///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
	/// </summary>
	// Этот класс создан автоматически классом StronglyTypedResourceBuilder
	// с помощью такого средства, как ResGen или Visual Studio.
	// Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
	// с параметром /str или перестройте свой проект VS.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class stringsRu {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal stringsRu() {
		}
		
		/// <summary>
		///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("pmd2mqoGUI.stringsRu", typeof(stringsRu).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Перезаписывает свойство CurrentUICulture текущего потока для всех
		///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Ищет локализованную строку, похожую на Выбрать файл.
		/// </summary>
		internal static string chooseFile {
			get {
				return ResourceManager.GetString("chooseFile", resourceCulture);
			}
		}
		
		/// <summary>
		///   Ищет локализованную строку, похожую на Инфо:.
		/// </summary>
		internal static string comment {
			get {
				return ResourceManager.GetString("comment", resourceCulture);
			}
		}
		
		/// <summary>
		///   Ищет локализованную строку, похожую на Выполнить.
		/// </summary>
		internal static string convert {
			get {
				return ResourceManager.GetString("convert", resourceCulture);
			}
		}
		
		/// <summary>
		///   Ищет локализованную строку, похожую на Выполнено успешно.
		///
		///При копировании не забудьте
		///скопировать и файлы текстур!.
		/// </summary>
		internal static string doneCorrectly {
			get {
				return ResourceManager.GetString("doneCorrectly", resourceCulture);
			}
		}
		
		/// <summary>
		///   Ищет локализованную строку, похожую на Ошибка!.
		/// </summary>
		internal static string error {
			get {
				return ResourceManager.GetString("error", resourceCulture);
			}
		}
		
		/// <summary>
		///   Ищет локализованную строку, похожую на Информация о файле:.
		/// </summary>
		internal static string fileInfo {
			get {
				return ResourceManager.GetString("fileInfo", resourceCulture);
			}
		}
		
		/// <summary>
		///   Ищет локализованную строку, похожую на Вход:.
		/// </summary>
		internal static string input {
			get {
				return ResourceManager.GetString("input", resourceCulture);
			}
		}
		
		/// <summary>
		///   Ищет локализованную строку, похожую на Пожалуйста, выберите PMD-файл.
		/// </summary>
		internal static string inputHelp {
			get {
				return ResourceManager.GetString("inputHelp", resourceCulture);
			}
		}
		
		/// <summary>
		///   Ищет локализованную строку, похожую на Имя:.
		/// </summary>
		internal static string name {
			get {
				return ResourceManager.GetString("name", resourceCulture);
			}
		}
		
		/// <summary>
		///   Ищет локализованную строку, похожую на Ошибка конвертирования:
		///Файл не в формате PMD!.
		/// </summary>
		internal static string notPmdError {
			get {
				return ResourceManager.GetString("notPmdError", resourceCulture);
			}
		}
		
		/// <summary>
		///   Ищет локализованную строку, похожую на Выход:.
		/// </summary>
		internal static string output {
			get {
				return ResourceManager.GetString("output", resourceCulture);
			}
		}
		
		/// <summary>
		///   Ищет локализованную строку, похожую на Размер:.
		/// </summary>
		internal static string scale {
			get {
				return ResourceManager.GetString("scale", resourceCulture);
			}
		}
		
		/// <summary>
		///   Ищет локализованную строку, похожую на Некоторые текстуры не были найдены!
		///Возможны ошибки при импорте такого файла.
		///
		///Список не найденных текстур:
		///.
		/// </summary>
		internal static string texNotFound {
			get {
				return ResourceManager.GetString("texNotFound", resourceCulture);
			}
		}
		
		/// <summary>
		///   Ищет локализованную строку, похожую на Предупреждение.
		/// </summary>
		internal static string warning {
			get {
				return ResourceManager.GetString("warning", resourceCulture);
			}
		}
	}
}
